---
roles:
  rhel-7-mm-ha:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - type: shell
        name: "nameserver"
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
        sync_hosts: true
      - type: shell
        name: "mattermostsetup"
        path: "scripts/rhel7.sh"
  rhel-6-mm-ha:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - type: shell
        name: "nameserver"
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
        sync_hosts: true
      - type: shell
        name: "mattermostsetup"
        path: "scripts/rhel6.sh"
  ubuntu-14.04-mm-ha:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - type: shell
        name: "nameserver"
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
        sync_hosts: true
      - type: shell
        name: "mattermostsetup"
        path: "scripts/ubuntu1404.sh"
  ubuntu-16.04-mm-ha:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - type: shell
        name: "nameserver"
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
        sync_hosts: true
      - type: shell
        name: "mattermostsetup"
        path: "scripts/ubuntu1604.sh"
  haproxy:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - type: shell
        name: "nameserver"
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
        sync_hosts: true
      - type: shell
        name: "haproxysetup"
        path: "scripts/haproxy.sh"
